update snippet to support preseed
Change-Id: I8442758ffaf3a55ec4773bf820bc4cdefb2e6452

diff --git a/cobbler/snippets/preseed_post_install_network_config b/cobbler/snippets/preseed_post_install_network_config
--- a/cobbler/snippets/preseed_post_install_network_config
+++ b/cobbler/snippets/preseed_post_install_network_config
@@ -1,4 +1,9 @@
-# Start post_install_network_config generated code 
+## Start post_install_network_config generated code
+#if $getVar('promisc_nics', '') != ""
+    #set promisc_interfaces = [promisc.strip() for promisc in $promisc_nics.split(',') if promisc.strip()]
+#else
+    #set promisc_interfaces = []
+#end if
 #if $getVar("system_name","") != ""
     ## this is being provisioned by system records, not profile records
     ## so we can do the more complex stuff
@@ -47,11 +52,9 @@
     ## end looping through the interfaces to see which ones we need to configure.
     ## =============================================================================
     ## Rewrite the interfaces file and make sure we preserve the loopback device
-rm -f /etc/network/interfaces 
-touch /etc/network/interfaces 
-echo "auto lo" >> /etc/network/interfaces 
-echo "iface lo inet loopback" >> /etc/network/interfaces 
-echo "" >> /etc/network/interfaces 
+echo "auto lo" > /target/etc/network/interfaces; \
+echo "   iface lo inet loopback" >> /target/etc/network/interfaces; \
+echo "" >> /target/etc/network/interfaces; \
     ## =============================================================================
     ## now create the config file for each interface
     #for $iname in $ikeys
@@ -60,6 +63,7 @@ echo "" >> /etc/network/interfaces
         #set $mac                  = $idata.get("mac_address", "").upper()
         #set $mtu                  = $idata.get("mtu", "")
         #set $static               = $idata.get("static", "")
+        #set $management           = $idata.get("management", "")
         #set $ip                   = $idata.get("ip_address", "")
         #set $netmask              = $idata.get("netmask", "")
         #set $if_gateway           = $idata.get("if_gateway", "")
@@ -73,9 +77,9 @@ echo "" >> /etc/network/interfaces
         #set $ipv6_mtu             = $idata.get("ipv6_mtu", "")
         #set $ipv6_default_gateway = $idata.get("ipv6_default_gateway", "")
         #set $ipv6_static_routes   = $idata.get("ipv6_static_routes", "")
-        #set $devfile              = "/etc/sysconfig/network-scripts/cobbler/ifcfg-" + $iname
-        #set $routesfile           = "/etc/sysconfig/network-scripts/cobbler/route-" + $iname
-        #set $ipv6_routesfile      = "/etc/sysconfig/network-scripts/cobbler/route6-" + $iname
+        #set $devfile              = "/target/etc/sysconfig/network-scripts/cobbler/ifcfg-" + $iname
+        #set $routesfile           = "/target/etc/sysconfig/network-scripts/cobbler/route-" + $iname
+        #set $ipv6_routesfile      = "/target/etc/sysconfig/network-scripts/cobbler/route6-" + $iname
         ## determine if this interface is for a VLAN
         #if $vlanpattern.match($iname)
             #set $is_vlan = "true"
@@ -89,35 +93,31 @@ echo "" >> /etc/network/interfaces
         ## ===================================================================
         ## Things every interface get, no matter what
         ## ===================================================================
-echo "auto $iname" >> /etc/network/interfaces 
-        ## ===================================================================
-        ## Actions based on interface_type
-        ## ===================================================================
-        #if $iface_type in ("master","bond","bonded_bridge_slave")
-          #pass
-        #elif $iface_type in ("slave","bond_slave") and $iface_master != ""
-          #pass
-        #elif $iface_type == "bridge"
-          #set $slave_ports = " ".join($bridge_slaves.get($iname,[]))
-          #if $slave_ports != ""
-echo "  bridge_ports $slave_ports" >> /etc/network/interfaces 
-          #end if
-          #for $bridge_opt in $bridge_opts
-            #if $bridge_opt.strip() != ""
-echo "  $bridge_opt" >> /etc/network/interfaces 
-            #end if
-          #end for
-        #end if
+echo "auto $iname" >> /target/etc/network/interfaces; \
         ## ===================================================================
         ## Actions based on static configuration
         ## ===================================================================
         #if $static
-            #if $ip != "" and $iface_type not in ("slave","bond_slave","bridge_slave","bonded_bridge_slave")
-echo "iface $iname inet static" >> /etc/network/interfaces 
-echo "   hwaddress $mac" >> /etc/network/interfaces
-echo "   address $ip" >> /etc/network/interfaces 
-                #if $netmask != ""
-echo "   netmask $netmask" >> /etc/network/interfaces 
+            #if $iface_type not in ("slave","bond_slave","bridge_slave","bonded_bridge_slave")
+echo "iface $iname inet static" >> /target/etc/network/interfaces; \
+                #if $mac != ""
+echo "   hwaddress $mac" >> /target/etc/network/interfaces; \
+                #end if
+                #if $iname in $promisc_interfaces
+echo "   up ifconfig $iname promisc up" >> /target/etc/network/interfaces; \
+echo "   down ifconfig $iname promisc down" >> /target/etc/network/interfaces; \
+                #else
+                    #if $ip != ""
+echo "   address $ip" >> /target/etc/network/interfaces; \
+                    #end if
+                    #if $if_gateway != ""
+echo "   gateway $if_gateway" >> /target/etc/network/interfaces; \
+                    #end if
+                    #if $netmask == ""
+                        ## Default to 255.255.255.0?
+                        #set $netmask = "255.255.255.0"
+                    #end if
+echo "   netmask $netmask" >> /target/etc/network/interfaces; \
                 #end if
                 #if $iface_type in ("master","bond")
                   #set $bondslaves = ""
@@ -129,34 +129,20 @@ echo "   netmask $netmask" >> /etc/network/interfaces
                          #set $bondslaves += $bondiname + " "
                       #end if
                   #end for
-echo "   bond-slaves $bondslaves" >> /etc/network/interfaces
-		  #for $bondopts in $bonding_opts.split(" ")
-		      #set [$bondkey, $bondvalue] = $bondopts.split("=")
-echo "   bond-$bondkey $bondvalue" >> /etc/network/interfaces
-                  #end for
+echo "   bond-slaves $bondslaves" >> /target/etc/network/interfaces; \
+		    #for $bondopts in $bonding_opts.split(" ")
+		        #set [$bondkey, $bondvalue] = $bondopts.split("=")
+echo "   bond-$bondkey $bondvalue" >> /target/etc/network/interfaces; \
+                    #end for
                 #end if
             #else
-echo "iface $iname inet manual" >> /etc/network/interfaces 
+echo "iface $iname inet manual" >> /target/etc/network/interfaces; \
             #end if
             #if $iface_type in ("slave","bond_slave") and $iface_master != ""
-echo "bond-master $iface_master" >> /etc/network/interfaces
-            #end if
-            #if $enableipv6 == True and $ipv6_autoconfiguration == False
-                #if $ipv6_address != ""
-                  #pass
-                #end if
-                #if $ipv6_secondaries != ""
-                    #set ipv6_secondaries = ' '.join(ipv6_secondaries)
-                #end if
-                #if $ipv6_mtu != ""
-                  #pass
-                #end if
-                #if $ipv6_default_gateway != ""
-                  #pass
-                #end if
+echo "bond-master $iface_master" >> /target/etc/network/interfaces; \
             #end if
         #else
-echo "iface $iname inet dhcp" >> /etc/network/interfaces 
+echo "iface $iname inet dhcp" >> /target/etc/network/interfaces; \
         #end if
         ## ===================================================================
         ## VLAN configuration
@@ -167,11 +153,8 @@ echo "iface $iname inet dhcp" >> /etc/network/interfaces
         ## ===================================================================
         ## Optional configuration stuff
         ## ===================================================================
-        #if $if_gateway != ""
-echo "   gateway $if_gateway" >> /etc/network/interfaces
-        #end if
         #if $mtu != ""
-echo "   mtu $mtu" >> /etc/network/interfaces
+echo "   mtu $mtu" >> /target/etc/network/interfaces; \
         #end if
         ## ===================================================================
         ## Interface route configuration
@@ -180,9 +163,9 @@ echo "   mtu $mtu" >> /etc/network/interfaces
             #set routepattern = $re.compile("[0-9/.]+:[0-9.]+")
             #if $routepattern.match($route)
                 #set [$network, $router] = $route.split(":")
-echo "   up ip route add $network via $router dev $iname || true" >> /etc/network/interfaces
+echo "   up ip route add $network via $router dev $iname || true" >> /target/etc/network/interfaces; \
             #else
-echo "   # Warning: invalid route: $route" >> /etc/network/interfaces
+echo "   # Warning: invalid route: $route" >> /target/etc/network/interfaces; \
             #end if
         #end for
         #if $enableipv6 == True
@@ -190,12 +173,28 @@ echo "   # Warning: invalid route: $route" >> /etc/network/interfaces
                 #set routepattern = $re.compile("[0-9a-fA-F:/]+,[0-9a-fA-F:]+")
                 #if $routepattern.match($route)
                     #set [$network, $router] = $route.split(",")
-echo "   up ip -6 route add $network via $router dev $iname || true" >> /etc/network/interfaces
+echo "   up ip -6 route add $network via $router dev $iname || true" >> /target/etc/network/interfaces; \
                 #else
-echo "   # Warning: invalid route: $route" >> /etc/network/interfaces
+echo "   # Warning: invalid route: $route" >> /target/etc/network/interfaces; \
                 #end if
             #end for
         #end if
+        #if $management
+            #if $gateway != "" and $if_gateway == ""
+echo "   gateway $gateway" >> /target/etc/network/interfaces; \
+            #end if
+            ## =============================================================================
+            ## Configure name server search path in /target/etc/resolv.conf
+            #set $nameservers = ' '.join($name_servers)
+            #set $nameserver_search = ' '.join($name_servers_search)
+            #if $nameservers != ""
+echo "   dns-nameservers $nameservers" >> /target/etc/network/interfaces; \
+            #end if
+            #if $nameserver_search != ""
+echo "   dns-search $nameserver_search" >> /target/etc/network/interfaces; \
+            #end if
+        #end if
+echo "" >> /target/etc/network/interfaces; \
         ## ===================================================================
         ## Done with this interface
         ## ===================================================================
@@ -204,28 +203,8 @@ echo "   # Warning: invalid route: $route" >> /etc/network/interfaces
     ## Configure the system's primary hostname. This is also passed to anaconda, but
     ## anaconda doesn't seem to honour it in DHCP-setups.
     #if $hostname != ""
-echo "$hostname" > /etc/hostname 
-/bin/hostname $hostname 
+echo "$hostname" > /target/etc/hostname; \
     #end if
-    ## =============================================================================
-    ## Configure name server search path in /etc/resolv.conf
-    #set $num_ns = $len($name_servers)
-    #set $num_ns_search = $len($name_servers_search)
-    #if $num_ns_search > 0
-sed -i -e "/^search /d" /etc/resolv.conf 
-echo -n "search " >>/etc/resolv.conf 
-        #for $nameserversearch in $name_servers_search
-echo -n "$nameserversearch " >>/etc/resolv.conf 
-        #end for
-echo "" >>/etc/resolv.conf 
-    #end if
-    ## =============================================================================
-    ## Configure name servers in /etc/resolv.conf
-    #if $num_ns > 0
-sed -i -e "/^nameserver /d" /etc/resolv.conf 
-        #for $nameserver in $name_servers
-echo "nameserver $nameserver" >>/etc/resolv.conf 
-        #end for
-    #end if
+$SNIPPET('preseed_hosts') echo "processed preseed_hosts" >> /tmp/preseed.log; \
 #end if
-# End post_install_network_config generated code 
+## End post_install_network_config generated code 
